# Generated by Django 3.2.25 on 2026-05-10 04:37

from django.db import migrations, models
import graphics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=50)),
                ('date', models.DateField(default=graphics.models.fecha_actual)),
            ],
        ),
    ]
